#!/bin/bash

if [ -f $HOME/.xinitrc ]; then
    . $HOME/.xinitrc
fi
if which dwmstatus &>/dev/null && [ -x "$(which dwmstatus)" ]; then
    while pgrep X &>/dev/null ; do sleep 5; dwmstatus; done &
fi
exec dwm
